USE ROLE ACCOUNTADMIN;
USE DATABASE {env}_NMIS_ETL_PIPELINE;

CREATE SCHEMA IF NOT EXISTS SALESFORCE;

CREATE OR REPLACE TABLE SALESFORCE.POLICY (
    -- Standard Salesforce fields
    id                                          VARCHAR(18)     NOT NULL,
    owner_id                                    VARCHAR(18),
    is_deleted                                  BOOLEAN,
    name                                        VARCHAR,
    record_type_id                              VARCHAR(18),
    created_date                                TIMESTAMP_TZ,
    created_by_id                               VARCHAR(18),
    last_modified_date                          TIMESTAMP_TZ,
    last_modified_by_id                         VARCHAR(18),
    system_modstamp                             TIMESTAMP_TZ,
    last_activity_date                          DATE,
    last_viewed_date                            DATE,
    last_referenced_date                        DATE,

    -- Custom fields
    agency__c                                   VARCHAR(18),
    available_recovery__c                       NUMBER(18, 4),
    brokerage_percent_of_gross_premium__c       NUMBER(18, 4),
    carrier__c                                  VARCHAR(18),
    cover_type_1__c                             VARCHAR,
    cover_type_2__c                             VARCHAR,
    cover_type_3__c                             VARCHAR,
    coverholder_name__c                         VARCHAR,
    date_first_written__c                       DATE,
    effective_date__c                           DATE,
    expiration_date__c                          DATE,
    location_of_risk_county__c                  VARCHAR,
    named_insured__c                            VARCHAR(18),
    number_of_transactions__c                   NUMBER(18, 0),
    oldpolicy__c                                VARCHAR(18),
    period_of_cover_narrative__c               NUMBER(18, 4),
    policy_basis__c                             VARCHAR,
    policy_number__c                            VARCHAR,
    policy_status__c                            VARCHAR,
    policy_term__c                              NUMBER(18, 4),
    producer__c                                 VARCHAR(18),
    producing_agent__c                          VARCHAR(18),
    product__c                                  VARCHAR(18),
    quote__c                                    VARCHAR(18),
    reference_number__c                         VARCHAR,
    reinsurance_basis__c                        VARCHAR,
    renewal_of__c                               VARCHAR(18),
    risk_code__c                                VARCHAR,
    sales_lead__c                               VARCHAR(18),
    sum_insured_amount__c                       NUMBER(18, 4),
    sum_insured_currency__c                     VARCHAR,
    surplus_lines_broker_country__c             VARCHAR,
    surplus_lines_license__c                    VARCHAR(18),
    tria_accepted__c                            BOOLEAN,
    tria_premium__c                             NUMBER(18, 4),
    tria_sign_date__c                           DATE,
    total_gross_written_premium__c              NUMBER(18, 4),
    type_of_insurance__c                        VARCHAR,
    us_classification_of_risk__c               VARCHAR,
    agreement_no__c                             VARCHAR,
    coverholder_pin__c                          VARCHAR,
    industrial_sector_of_the_insured__c        VARCHAR,
    insured_country__c                          VARCHAR,
    insured_full_name__c                        VARCHAR,
    insured_state_province_territory__c         VARCHAR,
    naic_code__c                                VARCHAR,
    peril__c                                    VARCHAR,
    risk_expiry_date__c                         DATE,
    risk_inception_date__c                      DATE,
    surplus_lines_broker_address__c             VARCHAR,
    surplus_lines_broker_name__c                VARCHAR,
    surplus_lines_broker_state__c               VARCHAR,
    surplus_lines_broker_zip_code__c            VARCHAR,
    unique_market_reference__c                  VARCHAR,
    year_of_account__c                          VARCHAR,
    location_of_risk_country__c                 VARCHAR,
    state_of_filing__c                          VARCHAR,
    location_of_risk_state_province__c          VARCHAR,
    active_underwriter_discretionary_discoun__c BOOLEAN,
    complex_risk__c                             BOOLEAN,
    declination_reason__c                       VARCHAR,
    loss_reason__c                              VARCHAR,
    referred_to_pricing_group__c                BOOLEAN,
    submission__c                               VARCHAR(18),
    brokerage_name__c                           VARCHAR,
    product_conga__c                            VARCHAR,
    total_indemnity_paid__c                     NUMBER(18, 4),
    remaining_limit__c                          NUMBER(18, 4),
    account_type__c                             VARCHAR,
    insurance_type__c                           VARCHAR,
    risk_code_formula__c                        VARCHAR,
    diligence_search__c                         BOOLEAN,
    number_of_transactions_rollup__c            NUMBER(18, 0),
    total_gross_written_premium_rollup__c       NUMBER(18, 4),
    sharepoint_folder__c                        VARCHAR,
    taxes_paid_by_brooker__c                    BOOLEAN,
    surplus_lines_license_agent__c              VARCHAR(18),
    surplus_lines_license_number__c             VARCHAR,
    surplus_lines_license_state__c              VARCHAR,
    quote_prepared_by__c                        VARCHAR(18),
    unique_market_reference_om__c               VARCHAR,
    record_type_name__c                         VARCHAR,
    premium_subtracted__c                       BOOLEAN,
    has_sublimit__c                             BOOLEAN,
    peril_picklist__c                           VARCHAR,
    policy_number_formula__c                    VARCHAR,
    policy_expired__c                           BOOLEAN,
    policy_forms_generated__c                   BOOLEAN,
    invoice_forms_generated__c                  BOOLEAN,

    -- Prod-only fields
    surplus_lines_agency_name__c                VARCHAR,
    surplus_lines_broker_city__c                VARCHAR,
    producer_formula__c                         VARCHAR,
    number_of_claims__c                         NUMBER(18, 0),
    number_of_denied_claims__c                  NUMBER(18, 0),
    agent_incentive_program__c                  VARCHAR,
    bound_via__c                                VARCHAR,
    year_of_account_om__c                       VARCHAR,
    entity_type__c                              VARCHAR,
    parent_brokerage_name__c                    VARCHAR,

    PRIMARY KEY (id)
);

CREATE OR REPLACE TABLE SALESFORCE.POLICY_STAGING LIKE SALESFORCE.POLICY;