USE ROLE ACCOUNTADMIN;
USE DATABASE {env}_NMIS_ETL_PIPELINE;

ALTER TABLE SALESFORCE.POLICY_STAGING SET DATA_RETENTION_TIME_IN_DAYS = 90;

CREATE OR REPLACE STREAM SALESFORCE.POLICY_STAGING_STREAM
    ON TABLE SALESFORCE.POLICY_STAGING;

CREATE OR REPLACE TASK SALESFORCE.POLICY_MERGE_TASK
    USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
    SCHEDULE  = '5 MINUTES'
    SUSPEND_TASK_AFTER_NUM_FAILURES = 0
    WHEN SYSTEM$STREAM_HAS_DATA('SALESFORCE.POLICY_STAGING_STREAM')
AS
    MERGE INTO SALESFORCE.POLICY AS target
    USING (
        SELECT * FROM SALESFORCE.POLICY_STAGING
        QUALIFY ROW_NUMBER() OVER (PARTITION BY id ORDER BY last_modified_date DESC NULLS LAST) = 1
    ) AS source
    ON target.id = source.id
    WHEN MATCHED AND source.is_deleted = TRUE THEN DELETE
    WHEN MATCHED THEN UPDATE SET
        owner_id                                    = source.owner_id,
        is_deleted                                  = source.is_deleted,
        name                                        = source.name,
        record_type_id                              = source.record_type_id,
        last_modified_date                          = source.last_modified_date,
        last_modified_by_id                         = source.last_modified_by_id,
        system_modstamp                             = source.system_modstamp,
        last_activity_date                          = source.last_activity_date,
        last_viewed_date                            = source.last_viewed_date,
        last_referenced_date                        = source.last_referenced_date,
        agency__c                                   = source.agency__c,
        available_recovery__c                       = source.available_recovery__c,
        brokerage_percent_of_gross_premium__c       = source.brokerage_percent_of_gross_premium__c,
        carrier__c                                  = source.carrier__c,
        cover_type_1__c                             = source.cover_type_1__c,
        cover_type_2__c                             = source.cover_type_2__c,
        cover_type_3__c                             = source.cover_type_3__c,
        coverholder_name__c                         = source.coverholder_name__c,
        date_first_written__c                       = source.date_first_written__c,
        effective_date__c                           = source.effective_date__c,
        expiration_date__c                          = source.expiration_date__c,
        location_of_risk_county__c                  = source.location_of_risk_county__c,
        named_insured__c                            = source.named_insured__c,
        number_of_transactions__c                   = source.number_of_transactions__c,
        oldpolicy__c                                = source.oldpolicy__c,
        period_of_cover_narrative__c                = source.period_of_cover_narrative__c,
        policy_basis__c                             = source.policy_basis__c,
        policy_number__c                            = source.policy_number__c,
        policy_status__c                            = source.policy_status__c,
        policy_term__c                              = source.policy_term__c,
        producer__c                                 = source.producer__c,
        producing_agent__c                          = source.producing_agent__c,
        product__c                                  = source.product__c,
        quote__c                                    = source.quote__c,
        reference_number__c                         = source.reference_number__c,
        reinsurance_basis__c                        = source.reinsurance_basis__c,
        renewal_of__c                               = source.renewal_of__c,
        risk_code__c                                = source.risk_code__c,
        sales_lead__c                               = source.sales_lead__c,
        sum_insured_amount__c                       = source.sum_insured_amount__c,
        sum_insured_currency__c                     = source.sum_insured_currency__c,
        surplus_lines_broker_country__c             = source.surplus_lines_broker_country__c,
        surplus_lines_license__c                    = source.surplus_lines_license__c,
        tria_accepted__c                            = source.tria_accepted__c,
        tria_premium__c                             = source.tria_premium__c,
        tria_sign_date__c                           = source.tria_sign_date__c,
        total_gross_written_premium__c              = source.total_gross_written_premium__c,
        type_of_insurance__c                        = source.type_of_insurance__c,
        us_classification_of_risk__c               = source.us_classification_of_risk__c,
        agreement_no__c                             = source.agreement_no__c,
        coverholder_pin__c                          = source.coverholder_pin__c,
        industrial_sector_of_the_insured__c        = source.industrial_sector_of_the_insured__c,
        insured_country__c                          = source.insured_country__c,
        insured_full_name__c                        = source.insured_full_name__c,
        insured_state_province_territory__c         = source.insured_state_province_territory__c,
        naic_code__c                                = source.naic_code__c,
        peril__c                                    = source.peril__c,
        risk_expiry_date__c                         = source.risk_expiry_date__c,
        risk_inception_date__c                      = source.risk_inception_date__c,
        surplus_lines_broker_address__c             = source.surplus_lines_broker_address__c,
        surplus_lines_broker_name__c                = source.surplus_lines_broker_name__c,
        surplus_lines_broker_state__c               = source.surplus_lines_broker_state__c,
        surplus_lines_broker_zip_code__c            = source.surplus_lines_broker_zip_code__c,
        unique_market_reference__c                  = source.unique_market_reference__c,
        year_of_account__c                          = source.year_of_account__c,
        location_of_risk_country__c                 = source.location_of_risk_country__c,
        state_of_filing__c                          = source.state_of_filing__c,
        location_of_risk_state_province__c          = source.location_of_risk_state_province__c,
        active_underwriter_discretionary_discoun__c = source.active_underwriter_discretionary_discoun__c,
        complex_risk__c                             = source.complex_risk__c,
        declination_reason__c                       = source.declination_reason__c,
        loss_reason__c                              = source.loss_reason__c,
        referred_to_pricing_group__c                = source.referred_to_pricing_group__c,
        submission__c                               = source.submission__c,
        brokerage_name__c                           = source.brokerage_name__c,
        product_conga__c                            = source.product_conga__c,
        total_indemnity_paid__c                     = source.total_indemnity_paid__c,
        remaining_limit__c                          = source.remaining_limit__c,
        account_type__c                             = source.account_type__c,
        insurance_type__c                           = source.insurance_type__c,
        risk_code_formula__c                        = source.risk_code_formula__c,
        diligence_search__c                         = source.diligence_search__c,
        number_of_transactions_rollup__c            = source.number_of_transactions_rollup__c,
        total_gross_written_premium_rollup__c       = source.total_gross_written_premium_rollup__c,
        sharepoint_folder__c                        = source.sharepoint_folder__c,
        taxes_paid_by_brooker__c                    = source.taxes_paid_by_brooker__c,
        surplus_lines_license_agent__c              = source.surplus_lines_license_agent__c,
        surplus_lines_license_number__c             = source.surplus_lines_license_number__c,
        surplus_lines_license_state__c              = source.surplus_lines_license_state__c,
        quote_prepared_by__c                        = source.quote_prepared_by__c,
        unique_market_reference_om__c               = source.unique_market_reference_om__c,
        record_type_name__c                         = source.record_type_name__c,
        premium_subtracted__c                       = source.premium_subtracted__c,
        has_sublimit__c                             = source.has_sublimit__c,
        peril_picklist__c                           = source.peril_picklist__c,
        policy_number_formula__c                    = source.policy_number_formula__c,
        policy_expired__c                           = source.policy_expired__c,
        policy_forms_generated__c                   = source.policy_forms_generated__c,
        invoice_forms_generated__c                  = source.invoice_forms_generated__c,
        surplus_lines_agency_name__c                = source.surplus_lines_agency_name__c,
        surplus_lines_broker_city__c                = source.surplus_lines_broker_city__c,
        producer_formula__c                         = source.producer_formula__c,
        number_of_claims__c                         = source.number_of_claims__c,
        number_of_denied_claims__c                  = source.number_of_denied_claims__c,
        agent_incentive_program__c                  = source.agent_incentive_program__c,
        bound_via__c                                = source.bound_via__c,
        year_of_account_om__c                       = source.year_of_account_om__c,
        entity_type__c                              = source.entity_type__c,
        parent_brokerage_name__c                    = source.parent_brokerage_name__c
    WHEN NOT MATCHED THEN INSERT (
        id, owner_id, is_deleted, name, record_type_id, created_date, created_by_id,
        last_modified_date, last_modified_by_id, system_modstamp, last_activity_date,
        last_viewed_date, last_referenced_date, agency__c, available_recovery__c,
        brokerage_percent_of_gross_premium__c, carrier__c, cover_type_1__c, cover_type_2__c,
        cover_type_3__c, coverholder_name__c, date_first_written__c, effective_date__c,
        expiration_date__c, location_of_risk_county__c, named_insured__c,
        number_of_transactions__c, oldpolicy__c, period_of_cover_narrative__c, policy_basis__c,
        policy_number__c, policy_status__c, policy_term__c, producer__c, producing_agent__c,
        product__c, quote__c, reference_number__c, reinsurance_basis__c, renewal_of__c,
        risk_code__c, sales_lead__c, sum_insured_amount__c, sum_insured_currency__c,
        surplus_lines_broker_country__c, surplus_lines_license__c, tria_accepted__c,
        tria_premium__c, tria_sign_date__c, total_gross_written_premium__c, type_of_insurance__c,
        us_classification_of_risk__c, agreement_no__c, coverholder_pin__c,
        industrial_sector_of_the_insured__c, insured_country__c, insured_full_name__c,
        insured_state_province_territory__c, naic_code__c, peril__c, risk_expiry_date__c,
        risk_inception_date__c, surplus_lines_broker_address__c, surplus_lines_broker_name__c,
        surplus_lines_broker_state__c, surplus_lines_broker_zip_code__c,
        unique_market_reference__c, year_of_account__c, location_of_risk_country__c,
        state_of_filing__c, location_of_risk_state_province__c,
        active_underwriter_discretionary_discoun__c, complex_risk__c, declination_reason__c,
        loss_reason__c, referred_to_pricing_group__c, submission__c, brokerage_name__c,
        product_conga__c, total_indemnity_paid__c, remaining_limit__c, account_type__c,
        insurance_type__c, risk_code_formula__c, diligence_search__c,
        number_of_transactions_rollup__c, total_gross_written_premium_rollup__c,
        sharepoint_folder__c, taxes_paid_by_brooker__c, surplus_lines_license_agent__c,
        surplus_lines_license_number__c, surplus_lines_license_state__c, quote_prepared_by__c,
        unique_market_reference_om__c, record_type_name__c, premium_subtracted__c,
        has_sublimit__c, peril_picklist__c, policy_number_formula__c, policy_expired__c,
        policy_forms_generated__c, invoice_forms_generated__c, surplus_lines_agency_name__c,
        surplus_lines_broker_city__c, producer_formula__c, number_of_claims__c,
        number_of_denied_claims__c, agent_incentive_program__c, bound_via__c,
        year_of_account_om__c, entity_type__c, parent_brokerage_name__c
    ) VALUES (
        source.id, source.owner_id, source.is_deleted, source.name, source.record_type_id,
        source.created_date, source.created_by_id, source.last_modified_date,
        source.last_modified_by_id, source.system_modstamp, source.last_activity_date,
        source.last_viewed_date, source.last_referenced_date, source.agency__c,
        source.available_recovery__c, source.brokerage_percent_of_gross_premium__c,
        source.carrier__c, source.cover_type_1__c, source.cover_type_2__c,
        source.cover_type_3__c, source.coverholder_name__c, source.date_first_written__c,
        source.effective_date__c, source.expiration_date__c, source.location_of_risk_county__c,
        source.named_insured__c, source.number_of_transactions__c, source.oldpolicy__c,
        source.period_of_cover_narrative__c, source.policy_basis__c, source.policy_number__c,
        source.policy_status__c, source.policy_term__c, source.producer__c,
        source.producing_agent__c, source.product__c, source.quote__c,
        source.reference_number__c, source.reinsurance_basis__c, source.renewal_of__c,
        source.risk_code__c, source.sales_lead__c, source.sum_insured_amount__c,
        source.sum_insured_currency__c, source.surplus_lines_broker_country__c,
        source.surplus_lines_license__c, source.tria_accepted__c, source.tria_premium__c,
        source.tria_sign_date__c, source.total_gross_written_premium__c,
        source.type_of_insurance__c, source.us_classification_of_risk__c,
        source.agreement_no__c, source.coverholder_pin__c,
        source.industrial_sector_of_the_insured__c, source.insured_country__c,
        source.insured_full_name__c, source.insured_state_province_territory__c,
        source.naic_code__c, source.peril__c, source.risk_expiry_date__c,
        source.risk_inception_date__c, source.surplus_lines_broker_address__c,
        source.surplus_lines_broker_name__c, source.surplus_lines_broker_state__c,
        source.surplus_lines_broker_zip_code__c, source.unique_market_reference__c,
        source.year_of_account__c, source.location_of_risk_country__c,
        source.state_of_filing__c, source.location_of_risk_state_province__c,
        source.active_underwriter_discretionary_discoun__c, source.complex_risk__c,
        source.declination_reason__c, source.loss_reason__c,
        source.referred_to_pricing_group__c, source.submission__c, source.brokerage_name__c,
        source.product_conga__c, source.total_indemnity_paid__c, source.remaining_limit__c,
        source.account_type__c, source.insurance_type__c, source.risk_code_formula__c,
        source.diligence_search__c, source.number_of_transactions_rollup__c,
        source.total_gross_written_premium_rollup__c, source.sharepoint_folder__c,
        source.taxes_paid_by_brooker__c, source.surplus_lines_license_agent__c,
        source.surplus_lines_license_number__c, source.surplus_lines_license_state__c,
        source.quote_prepared_by__c, source.unique_market_reference_om__c,
        source.record_type_name__c, source.premium_subtracted__c, source.has_sublimit__c,
        source.peril_picklist__c, source.policy_number_formula__c, source.policy_expired__c,
        source.policy_forms_generated__c, source.invoice_forms_generated__c,
        source.surplus_lines_agency_name__c, source.surplus_lines_broker_city__c,
        source.producer_formula__c, source.number_of_claims__c, source.number_of_denied_claims__c,
        source.agent_incentive_program__c, source.bound_via__c, source.year_of_account_om__c,
        source.entity_type__c, source.parent_brokerage_name__c
    );

ALTER TASK SALESFORCE.POLICY_MERGE_TASK RESUME;