USE ROLE ACCOUNTADMIN;
USE DATABASE {env}_NMIS_ETL_PIPELINE;

ALTER TABLE SALESFORCE.POLICY         MODIFY COLUMN surplus_lines_license_agent__c VARCHAR;
ALTER TABLE SALESFORCE.POLICY_STAGING MODIFY COLUMN surplus_lines_license_agent__c VARCHAR;
