USE ROLE ACCOUNTADMIN;
USE DATABASE {env}_NMIS_ETL_PIPELINE;

CREATE SCHEMA IF NOT EXISTS SALESFORCE;

CREATE OR REPLACE TABLE SALESFORCE.STRUCTURE (
    -- Standard Salesforce fields
    id                                          VARCHAR(18)     NOT NULL,
    owner_id                                    VARCHAR(18),
    is_deleted                                  BOOLEAN,
    name                                        VARCHAR,
    record_type_id                              VARCHAR(18),
    created_date                                TIMESTAMP_TZ,
    created_by_id                               VARCHAR(18),
    last_modified_date                          TIMESTAMP_TZ,
    last_modified_by_id                         VARCHAR(18),
    system_modstamp                             TIMESTAMP_TZ,
    last_viewed_date                            DATE,
    last_referenced_date                        DATE,

    -- Custom fields
    calculation_agent_expense__c                NUMBER(18, 4),
    coverage__c                                 VARCHAR(18),
    expected_loss__c                            NUMBER(18, 10),
    inland_circle_factor__c                     NUMBER(18, 4),
    insurance_state_tax__c                      VARCHAR(18),
    limit_of_insurance__c                       NUMBER(18, 4),
    loss_cost_multiplier_lcm__c                 NUMBER(18, 4),
    market_broker_commissions__c                NUMBER(18, 4),
    minimum_rate__c                             NUMBER(18, 4),
    nmis_mga_commissions__c                     NUMBER(18, 4),
    other_brokerage_commissions__c              NUMBER(18, 4),
    policy_fee__c                               NUMBER(18, 4),
    product__c                                  VARCHAR(18),
    tax_exempt__c                               BOOLEAN,
    transaction__c                              VARCHAR(18),
    underwriting_fee__c                         NUMBER(18, 4),
    weatherflow_maintenance_expense__c          NUMBER(18, 4),
    wholesaler_retailer_commissions__c          NUMBER(18, 4),
    adjusted_base_premium__c                    NUMBER(18, 4),
    adjusted_base_rate__c                       NUMBER(18, 4),
    adjusted_expected_loss__c                   NUMBER(18, 10),
    annual_premium__c                           NUMBER(18, 4),
    calculation_agent_expense_cost__c           NUMBER(18, 4),
    gross_premium_excl_taxes_and_fees__c        NUMBER(18, 4),
    gross_rate_excl_taxes_and_fees__c           NUMBER(18, 4),
    net_premium__c                              NUMBER(18, 4),
    net_rate__c                                 NUMBER(18, 4),
    non_adjusted_base_rate__c                   NUMBER(18, 10),
    taxable_premium__c                          NUMBER(18, 4),
    total_commissions__c                        NUMBER(18, 4),
    weatherflow_maintenance_cost__c             NUMBER(18, 4),
    policy__c                                   VARCHAR(18),
    market_broker_commission_currency__c        NUMBER(18, 4),
    all_in_rate__c                              NUMBER(18, 4),
    anemometer_rating_factor__c                 NUMBER(18, 4),
    issued_policy__c                            VARCHAR(18),
    quote__c                                    VARCHAR(18),
    adjusted_base_premium_om__c                 NUMBER(18, 4),
    adjusted_base_rate_om__c                    NUMBER(18, 4),
    adjusted_expected_loss_om__c                NUMBER(18, 10),
    all_in_rate_om__c                           NUMBER(18, 4),
    annual_premium_om__c                        NUMBER(18, 4),
    calculation_agent_expense_cost_om__c        NUMBER(18, 4),
    gross_premium_excl_taxes_and_fees_om__c     NUMBER(18, 4),
    gross_rate_excl_taxes_and_fees_om__c        NUMBER(18, 4),
    net_premium_om__c                           NUMBER(18, 4),
    net_rate_om__c                              NUMBER(18, 4),
    non_adjusted_base_rate_om__c                NUMBER(18, 10),
    taxable_premium_om__c                       NUMBER(18, 4),
    total_commissions_om__c                     NUMBER(18, 4),
    weatherflow_maintenance_cost_om__c          NUMBER(18, 4),
    adjusted_loss_factor__c                     NUMBER(18, 10),
    mga_commission__c                           NUMBER(18, 4),
    other_surplus_line_taxes_amount__c          NUMBER(18, 4),
    policy_administrator_fee__c                 NUMBER(18, 4),
    rating_calculation__c                       VARCHAR,
    rating_type__c                              VARCHAR,
    retail_commsion_ammount__c                  NUMBER(18, 4),
    surplus_lines_taxes_amount_1__c             NUMBER(18, 4),
    surplus_lines_taxes_amount_2__c             NUMBER(18, 4),
    surplus_lines_taxes_description_1__c        VARCHAR,
    surplus_lines_taxes_description_2__c        VARCHAR,
    last_modified_date_user__c                  TIMESTAMP_TZ,
    last_modified_by_user__c                    VARCHAR(18),
    is_current_structure__c                     BOOLEAN,
    manual_override__c                          BOOLEAN,
    original_currency__c                        VARCHAR,
    day_s_exchange__c                           NUMBER(18, 4),
    limit_in_original_currency__c               NUMBER(18, 4),
    premium_in_original_currency__c             NUMBER(18, 4),
    stamp_date__c                               DATE,
    maximum_rate__c                             NUMBER(18, 4),
    calculate_rates__c                          BOOLEAN,
    other_brokerage_commissions_currency__c     NUMBER(18, 4),
    rms_peril_region__c                         VARCHAR,
    rms_version__c                              VARCHAR,
    anemometers__c                              VARCHAR,
    last_modify_date_user__c                    TIMESTAMP_TZ,
    last_modiofied_by_user__c                   VARCHAR(18),
    number_of_anemometer_ws_triggers__c         NUMBER(18, 0),
    number_of_ciac_triggers__c                  NUMBER(18, 0),
    number_of_proxy_ws_triggers__c              NUMBER(18, 0),
    number_of_triggers__c                       NUMBER(18, 0),
    hurricane_coverage_type__c                  VARCHAR,
    modeling_provider__c                        VARCHAR,

    PRIMARY KEY (id)
);

CREATE OR REPLACE TABLE SALESFORCE.STRUCTURE_STAGING LIKE SALESFORCE.STRUCTURE;