USE ROLE ACCOUNTADMIN;
USE DATABASE {env}_NMIS_ETL_PIPELINE;

CREATE OR REPLACE PIPE SALESFORCE.STRUCTURE_PIPE
    AUTO_INGEST = TRUE
    COMMENT = 'Auto-ingest Structure__c Parquet files from S3 data lake'
  AS
  COPY INTO SALESFORCE.STRUCTURE_STAGING (
      id, owner_id, is_deleted, name, record_type_id, created_date, created_by_id,
      last_modified_date, last_modified_by_id, system_modstamp, last_viewed_date,
      last_referenced_date, calculation_agent_expense__c, coverage__c, expected_loss__c,
      inland_circle_factor__c, insurance_state_tax__c, limit_of_insurance__c,
      loss_cost_multiplier_lcm__c, market_broker_commissions__c, minimum_rate__c,
      nmis_mga_commissions__c, other_brokerage_commissions__c, policy_fee__c,
      product__c, tax_exempt__c, transaction__c, underwriting_fee__c,
      weatherflow_maintenance_expense__c, wholesaler_retailer_commissions__c,
      adjusted_base_premium__c, adjusted_base_rate__c, adjusted_expected_loss__c,
      annual_premium__c, calculation_agent_expense_cost__c,
      gross_premium_excl_taxes_and_fees__c, gross_rate_excl_taxes_and_fees__c,
      net_premium__c, net_rate__c, non_adjusted_base_rate__c, taxable_premium__c,
      total_commissions__c, weatherflow_maintenance_cost__c, policy__c,
      market_broker_commission_currency__c, all_in_rate__c, anemometer_rating_factor__c,
      issued_policy__c, quote__c, adjusted_base_premium_om__c, adjusted_base_rate_om__c,
      adjusted_expected_loss_om__c, all_in_rate_om__c, annual_premium_om__c,
      calculation_agent_expense_cost_om__c, gross_premium_excl_taxes_and_fees_om__c,
      gross_rate_excl_taxes_and_fees_om__c, net_premium_om__c, net_rate_om__c,
      non_adjusted_base_rate_om__c, taxable_premium_om__c, total_commissions_om__c,
      weatherflow_maintenance_cost_om__c, adjusted_loss_factor__c, mga_commission__c,
      other_surplus_line_taxes_amount__c, policy_administrator_fee__c, rating_calculation__c,
      rating_type__c, retail_commsion_ammount__c, surplus_lines_taxes_amount_1__c,
      surplus_lines_taxes_amount_2__c, surplus_lines_taxes_description_1__c,
      surplus_lines_taxes_description_2__c, last_modified_date_user__c,
      last_modified_by_user__c, is_current_structure__c, manual_override__c,
      original_currency__c, day_s_exchange__c, limit_in_original_currency__c,
      premium_in_original_currency__c, stamp_date__c, maximum_rate__c, calculate_rates__c,
      other_brokerage_commissions_currency__c, rms_peril_region__c, rms_version__c,
      anemometers__c, last_modify_date_user__c, last_modiofied_by_user__c,
      number_of_anemometer_ws_triggers__c, number_of_ciac_triggers__c,
      number_of_proxy_ws_triggers__c, number_of_triggers__c, hurricane_coverage_type__c,
      modeling_provider__c
  )
  FROM (
      SELECT
          $1:"Id"::VARCHAR,
          $1:"OwnerId"::VARCHAR,
          $1:"IsDeleted"::BOOLEAN,
          $1:"Name"::VARCHAR,
          $1:"RecordTypeId"::VARCHAR,
          TRY_TO_TIMESTAMP_TZ($1:"CreatedDate"::VARCHAR, 'YYYY-MM-DD"T"HH24:MI:SS.FF3TZHTZM'),
          $1:"CreatedById"::VARCHAR,
          TRY_TO_TIMESTAMP_TZ($1:"LastModifiedDate"::VARCHAR, 'YYYY-MM-DD"T"HH24:MI:SS.FF3TZHTZM'),
          $1:"LastModifiedById"::VARCHAR,
          TRY_TO_TIMESTAMP_TZ($1:"SystemModstamp"::VARCHAR, 'YYYY-MM-DD"T"HH24:MI:SS.FF3TZHTZM'),
          TRY_TO_DATE($1:"LastViewedDate"::VARCHAR),
          TRY_TO_DATE($1:"LastReferencedDate"::VARCHAR),
          TRY_TO_NUMBER($1:"Calculation_Agent_Expense__c"::VARCHAR, 18, 4),
          $1:"Coverage__c"::VARCHAR,
          TRY_TO_NUMBER($1:"Expected_Loss__c"::VARCHAR, 18, 10),
          TRY_TO_NUMBER($1:"Inland_Circle_Factor__c"::VARCHAR, 18, 4),
          $1:"Insurance_State_Tax__c"::VARCHAR,
          TRY_TO_NUMBER($1:"Limit_of_Insurance__c"::VARCHAR, 18, 4),
          TRY_TO_NUMBER($1:"Loss_Cost_Multiplier_LCM__c"::VARCHAR, 18, 4),
          TRY_TO_NUMBER($1:"Market_Broker_Commissions__c"::VARCHAR, 18, 4),
          TRY_TO_NUMBER($1:"Minimum_Rate__c"::VARCHAR, 18, 4),
          TRY_TO_NUMBER($1:"NMIS_MGA_Commissions__c"::VARCHAR, 18, 4),
          TRY_TO_NUMBER($1:"Other_Brokerage_Commissions__c"::VARCHAR, 18, 4),
          TRY_TO_NUMBER($1:"Policy_Fee__c"::VARCHAR, 18, 4),
          $1:"Product__c"::VARCHAR,
          $1:"Tax_Exempt__c"::BOOLEAN,
          $1:"Transaction__c"::VARCHAR,
          TRY_TO_NUMBER($1:"Underwriting_Fee__c"::VARCHAR, 18, 4),
          TRY_TO_NUMBER($1:"Weatherflow_Maintenance_Expense__c"::VARCHAR, 18, 4),
          TRY_TO_NUMBER($1:"Wholesaler_Retailer_Commissions__c"::VARCHAR, 18, 4),
          TRY_TO_NUMBER($1:"Adjusted_Base_Premium__c"::VARCHAR, 18, 4),
          TRY_TO_NUMBER($1:"Adjusted_Base_Rate__c"::VARCHAR, 18, 4),
          TRY_TO_NUMBER($1:"Adjusted_Expected_Loss__c"::VARCHAR, 18, 10),
          TRY_TO_NUMBER($1:"Annual_Premium__c"::VARCHAR, 18, 4),
          TRY_TO_NUMBER($1:"Calculation_Agent_Expense_Cost__c"::VARCHAR, 18, 4),
          TRY_TO_NUMBER($1:"Gross_Premium_excl_Taxes_and_Fees__c"::VARCHAR, 18, 4),
          TRY_TO_NUMBER($1:"Gross_Rate_excl_Taxes_and_Fees__c"::VARCHAR, 18, 4),
          TRY_TO_NUMBER($1:"Net_Premium__c"::VARCHAR, 18, 4),
          TRY_TO_NUMBER($1:"Net_Rate__c"::VARCHAR, 18, 4),
          TRY_TO_NUMBER($1:"Non_Adjusted_Base_Rate__c"::VARCHAR, 18, 10),
          TRY_TO_NUMBER($1:"Taxable_Premium__c"::VARCHAR, 18, 4),
          TRY_TO_NUMBER($1:"Total_Commissions__c"::VARCHAR, 18, 4),
          TRY_TO_NUMBER($1:"Weatherflow_Maintenance_Cost__c"::VARCHAR, 18, 4),
          $1:"Policy__c"::VARCHAR,
          TRY_TO_NUMBER($1:"Market_Broker_Commission_Currency__c"::VARCHAR, 18, 4),
          TRY_TO_NUMBER($1:"All_In_Rate__c"::VARCHAR, 18, 4),
          TRY_TO_NUMBER($1:"Anemometer_Rating_Factor__c"::VARCHAR, 18, 4),
          $1:"Issued_Policy__c"::VARCHAR,
          $1:"Quote__c"::VARCHAR,
          TRY_TO_NUMBER($1:"Adjusted_Base_Premium_OM__c"::VARCHAR, 18, 4),
          TRY_TO_NUMBER($1:"Adjusted_Base_Rate_OM__c"::VARCHAR, 18, 4),
          TRY_TO_NUMBER($1:"Adjusted_Expected_Loss_OM__c"::VARCHAR, 18, 10),
          TRY_TO_NUMBER($1:"All_in_Rate_OM__c"::VARCHAR, 18, 4),
          TRY_TO_NUMBER($1:"Annual_Premium_OM__c"::VARCHAR, 18, 4),
          TRY_TO_NUMBER($1:"Calculation_Agent_Expense_Cost_OM__c"::VARCHAR, 18, 4),
          TRY_TO_NUMBER($1:"Gross_Premium_excl_Taxes_and_Fees_OM__c"::VARCHAR, 18, 4),
          TRY_TO_NUMBER($1:"Gross_Rate_excl_Taxes_and_Fees_OM__c"::VARCHAR, 18, 4),
          TRY_TO_NUMBER($1:"Net_Premium_OM__c"::VARCHAR, 18, 4),
          TRY_TO_NUMBER($1:"Net_Rate_OM__c"::VARCHAR, 18, 4),
          TRY_TO_NUMBER($1:"Non_Adjusted_Base_Rate_OM__c"::VARCHAR, 18, 10),
          TRY_TO_NUMBER($1:"Taxable_Premium_OM__c"::VARCHAR, 18, 4),
          TRY_TO_NUMBER($1:"Total_Commissions_OM__c"::VARCHAR, 18, 4),
          TRY_TO_NUMBER($1:"Weatherflow_Maintenance_Cost_OM__c"::VARCHAR, 18, 4),
          TRY_TO_NUMBER($1:"Adjusted_Loss_Factor__c"::VARCHAR, 18, 10),
          TRY_TO_NUMBER($1:"MGA_Commission__c"::VARCHAR, 18, 4),
          TRY_TO_NUMBER($1:"Other_Surplus_Line_Taxes_Amount__c"::VARCHAR, 18, 4),
          TRY_TO_NUMBER($1:"Policy_Administrator_Fee__c"::VARCHAR, 18, 4),
          $1:"Rating_Calculation__c"::VARCHAR,
          $1:"Rating_Type__c"::VARCHAR,
          TRY_TO_NUMBER($1:"Retail_Commsion_Ammount__c"::VARCHAR, 18, 4),
          TRY_TO_NUMBER($1:"Surplus_Lines_Taxes_Amount_1__c"::VARCHAR, 18, 4),
          TRY_TO_NUMBER($1:"Surplus_Lines_Taxes_Amount_2__c"::VARCHAR, 18, 4),
          $1:"Surplus_Lines_Taxes_Description_1__c"::VARCHAR,
          $1:"Surplus_Lines_Taxes_Description_2__c"::VARCHAR,
          TRY_TO_TIMESTAMP_TZ($1:"Last_Modified_Date_User__c"::VARCHAR, 'YYYY-MM-DD"T"HH24:MI:SS.FF3TZHTZM'),
          $1:"Last_Modified_By_User__c"::VARCHAR,
          $1:"Is_Current_Structure__c"::BOOLEAN,
          $1:"Manual_Override__c"::BOOLEAN,
          $1:"Original_Currency__c"::VARCHAR,
          TRY_TO_NUMBER($1:"Day_s_Exchange__c"::VARCHAR, 18, 4),
          TRY_TO_NUMBER($1:"Limit_in_Original_Currency__c"::VARCHAR, 18, 4),
          TRY_TO_NUMBER($1:"Premium_in_Original_Currency__c"::VARCHAR, 18, 4),
          TRY_TO_DATE($1:"Stamp_Date__c"::VARCHAR),
          TRY_TO_NUMBER($1:"Maximum_Rate__c"::VARCHAR, 18, 4),
          $1:"Calculate_Rates__c"::BOOLEAN,
          TRY_TO_NUMBER($1:"Other_Brokerage_Commissions_Currency__c"::VARCHAR, 18, 4),
          $1:"RMS_Peril_Region__c"::VARCHAR,
          $1:"RMS_Version__c"::VARCHAR,
          $1:"Anemometers__c"::VARCHAR,
          TRY_TO_TIMESTAMP_TZ($1:"Last_Modify_Date_User__c"::VARCHAR, 'YYYY-MM-DD"T"HH24:MI:SS.FF3TZHTZM'),
          $1:"Last_Modiofied_By_User__c"::VARCHAR,
          TRY_TO_NUMBER($1:"Number_of_Anemometer_WS_Triggers__c"::VARCHAR, 18, 0),
          TRY_TO_NUMBER($1:"Number_of_CIAC_Triggers__c"::VARCHAR, 18, 0),
          TRY_TO_NUMBER($1:"Number_of_Proxy_WS_Triggers__c"::VARCHAR, 18, 0),
          TRY_TO_NUMBER($1:"Number_of_Triggers__c"::VARCHAR, 18, 0),
          $1:"Hurricane_Coverage_Type__c"::VARCHAR,
          $1:"Modeling_Provider__c"::VARCHAR
      FROM @SALESFORCE.SALESFORCE_RAW/structure/
  )
  FILE_FORMAT = (FORMAT_NAME = SALESFORCE.PARQUET_FORMAT);