USE ROLE ACCOUNTADMIN;
USE DATABASE {env}_NMIS_ETL_PIPELINE;

ALTER TABLE SALESFORCE.STRUCTURE_STAGING SET DATA_RETENTION_TIME_IN_DAYS = 90;

CREATE OR REPLACE STREAM SALESFORCE.STRUCTURE_STAGING_STREAM
    ON TABLE SALESFORCE.STRUCTURE_STAGING;

CREATE OR REPLACE TASK SALESFORCE.STRUCTURE_MERGE_TASK
    USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
    SCHEDULE  = '5 MINUTES'
    SUSPEND_TASK_AFTER_NUM_FAILURES = 0
    WHEN SYSTEM$STREAM_HAS_DATA('SALESFORCE.STRUCTURE_STAGING_STREAM')
AS
    MERGE INTO SALESFORCE.STRUCTURE AS target
    USING (
        SELECT * FROM SALESFORCE.STRUCTURE_STAGING
        QUALIFY ROW_NUMBER() OVER (PARTITION BY id ORDER BY last_modified_date DESC NULLS LAST) = 1
    ) AS source
    ON target.id = source.id
    WHEN MATCHED AND source.is_deleted = TRUE THEN DELETE
    WHEN MATCHED THEN UPDATE SET
        owner_id                                    = source.owner_id,
        is_deleted                                  = source.is_deleted,
        name                                        = source.name,
        record_type_id                              = source.record_type_id,
        last_modified_date                          = source.last_modified_date,
        last_modified_by_id                         = source.last_modified_by_id,
        system_modstamp                             = source.system_modstamp,
        last_viewed_date                            = source.last_viewed_date,
        last_referenced_date                        = source.last_referenced_date,
        calculation_agent_expense__c                = source.calculation_agent_expense__c,
        coverage__c                                 = source.coverage__c,
        expected_loss__c                            = source.expected_loss__c,
        inland_circle_factor__c                     = source.inland_circle_factor__c,
        insurance_state_tax__c                      = source.insurance_state_tax__c,
        limit_of_insurance__c                       = source.limit_of_insurance__c,
        loss_cost_multiplier_lcm__c                 = source.loss_cost_multiplier_lcm__c,
        market_broker_commissions__c                = source.market_broker_commissions__c,
        minimum_rate__c                             = source.minimum_rate__c,
        nmis_mga_commissions__c                     = source.nmis_mga_commissions__c,
        other_brokerage_commissions__c              = source.other_brokerage_commissions__c,
        policy_fee__c                               = source.policy_fee__c,
        product__c                                  = source.product__c,
        tax_exempt__c                               = source.tax_exempt__c,
        transaction__c                              = source.transaction__c,
        underwriting_fee__c                         = source.underwriting_fee__c,
        weatherflow_maintenance_expense__c          = source.weatherflow_maintenance_expense__c,
        wholesaler_retailer_commissions__c          = source.wholesaler_retailer_commissions__c,
        adjusted_base_premium__c                    = source.adjusted_base_premium__c,
        adjusted_base_rate__c                       = source.adjusted_base_rate__c,
        adjusted_expected_loss__c                   = source.adjusted_expected_loss__c,
        annual_premium__c                           = source.annual_premium__c,
        calculation_agent_expense_cost__c           = source.calculation_agent_expense_cost__c,
        gross_premium_excl_taxes_and_fees__c        = source.gross_premium_excl_taxes_and_fees__c,
        gross_rate_excl_taxes_and_fees__c           = source.gross_rate_excl_taxes_and_fees__c,
        net_premium__c                              = source.net_premium__c,
        net_rate__c                                 = source.net_rate__c,
        non_adjusted_base_rate__c                   = source.non_adjusted_base_rate__c,
        taxable_premium__c                          = source.taxable_premium__c,
        total_commissions__c                        = source.total_commissions__c,
        weatherflow_maintenance_cost__c             = source.weatherflow_maintenance_cost__c,
        policy__c                                   = source.policy__c,
        market_broker_commission_currency__c        = source.market_broker_commission_currency__c,
        all_in_rate__c                              = source.all_in_rate__c,
        anemometer_rating_factor__c                 = source.anemometer_rating_factor__c,
        issued_policy__c                            = source.issued_policy__c,
        quote__c                                    = source.quote__c,
        adjusted_base_premium_om__c                 = source.adjusted_base_premium_om__c,
        adjusted_base_rate_om__c                    = source.adjusted_base_rate_om__c,
        adjusted_expected_loss_om__c                = source.adjusted_expected_loss_om__c,
        all_in_rate_om__c                           = source.all_in_rate_om__c,
        annual_premium_om__c                        = source.annual_premium_om__c,
        calculation_agent_expense_cost_om__c        = source.calculation_agent_expense_cost_om__c,
        gross_premium_excl_taxes_and_fees_om__c     = source.gross_premium_excl_taxes_and_fees_om__c,
        gross_rate_excl_taxes_and_fees_om__c        = source.gross_rate_excl_taxes_and_fees_om__c,
        net_premium_om__c                           = source.net_premium_om__c,
        net_rate_om__c                              = source.net_rate_om__c,
        non_adjusted_base_rate_om__c                = source.non_adjusted_base_rate_om__c,
        taxable_premium_om__c                       = source.taxable_premium_om__c,
        total_commissions_om__c                     = source.total_commissions_om__c,
        weatherflow_maintenance_cost_om__c          = source.weatherflow_maintenance_cost_om__c,
        adjusted_loss_factor__c                     = source.adjusted_loss_factor__c,
        mga_commission__c                           = source.mga_commission__c,
        other_surplus_line_taxes_amount__c          = source.other_surplus_line_taxes_amount__c,
        policy_administrator_fee__c                 = source.policy_administrator_fee__c,
        rating_calculation__c                       = source.rating_calculation__c,
        rating_type__c                              = source.rating_type__c,
        retail_commsion_ammount__c                  = source.retail_commsion_ammount__c,
        surplus_lines_taxes_amount_1__c             = source.surplus_lines_taxes_amount_1__c,
        surplus_lines_taxes_amount_2__c             = source.surplus_lines_taxes_amount_2__c,
        surplus_lines_taxes_description_1__c        = source.surplus_lines_taxes_description_1__c,
        surplus_lines_taxes_description_2__c        = source.surplus_lines_taxes_description_2__c,
        last_modified_date_user__c                  = source.last_modified_date_user__c,
        last_modified_by_user__c                    = source.last_modified_by_user__c,
        is_current_structure__c                     = source.is_current_structure__c,
        manual_override__c                          = source.manual_override__c,
        original_currency__c                        = source.original_currency__c,
        day_s_exchange__c                           = source.day_s_exchange__c,
        limit_in_original_currency__c               = source.limit_in_original_currency__c,
        premium_in_original_currency__c             = source.premium_in_original_currency__c,
        stamp_date__c                               = source.stamp_date__c,
        maximum_rate__c                             = source.maximum_rate__c,
        calculate_rates__c                          = source.calculate_rates__c,
        other_brokerage_commissions_currency__c     = source.other_brokerage_commissions_currency__c,
        rms_peril_region__c                         = source.rms_peril_region__c,
        rms_version__c                              = source.rms_version__c,
        anemometers__c                              = source.anemometers__c,
        last_modify_date_user__c                    = source.last_modify_date_user__c,
        last_modiofied_by_user__c                   = source.last_modiofied_by_user__c,
        number_of_anemometer_ws_triggers__c         = source.number_of_anemometer_ws_triggers__c,
        number_of_ciac_triggers__c                  = source.number_of_ciac_triggers__c,
        number_of_proxy_ws_triggers__c              = source.number_of_proxy_ws_triggers__c,
        number_of_triggers__c                       = source.number_of_triggers__c,
        hurricane_coverage_type__c                  = source.hurricane_coverage_type__c,
        modeling_provider__c                        = source.modeling_provider__c
    WHEN NOT MATCHED THEN INSERT (
        id, owner_id, is_deleted, name, record_type_id, created_date, created_by_id,
        last_modified_date, last_modified_by_id, system_modstamp, last_viewed_date,
        last_referenced_date, calculation_agent_expense__c, coverage__c, expected_loss__c,
        inland_circle_factor__c, insurance_state_tax__c, limit_of_insurance__c,
        loss_cost_multiplier_lcm__c, market_broker_commissions__c, minimum_rate__c,
        nmis_mga_commissions__c, other_brokerage_commissions__c, policy_fee__c,
        product__c, tax_exempt__c, transaction__c, underwriting_fee__c,
        weatherflow_maintenance_expense__c, wholesaler_retailer_commissions__c,
        adjusted_base_premium__c, adjusted_base_rate__c, adjusted_expected_loss__c,
        annual_premium__c, calculation_agent_expense_cost__c,
        gross_premium_excl_taxes_and_fees__c, gross_rate_excl_taxes_and_fees__c,
        net_premium__c, net_rate__c, non_adjusted_base_rate__c, taxable_premium__c,
        total_commissions__c, weatherflow_maintenance_cost__c, policy__c,
        market_broker_commission_currency__c, all_in_rate__c, anemometer_rating_factor__c,
        issued_policy__c, quote__c, adjusted_base_premium_om__c, adjusted_base_rate_om__c,
        adjusted_expected_loss_om__c, all_in_rate_om__c, annual_premium_om__c,
        calculation_agent_expense_cost_om__c, gross_premium_excl_taxes_and_fees_om__c,
        gross_rate_excl_taxes_and_fees_om__c, net_premium_om__c, net_rate_om__c,
        non_adjusted_base_rate_om__c, taxable_premium_om__c, total_commissions_om__c,
        weatherflow_maintenance_cost_om__c, adjusted_loss_factor__c, mga_commission__c,
        other_surplus_line_taxes_amount__c, policy_administrator_fee__c, rating_calculation__c,
        rating_type__c, retail_commsion_ammount__c, surplus_lines_taxes_amount_1__c,
        surplus_lines_taxes_amount_2__c, surplus_lines_taxes_description_1__c,
        surplus_lines_taxes_description_2__c, last_modified_date_user__c,
        last_modified_by_user__c, is_current_structure__c, manual_override__c,
        original_currency__c, day_s_exchange__c, limit_in_original_currency__c,
        premium_in_original_currency__c, stamp_date__c, maximum_rate__c, calculate_rates__c,
        other_brokerage_commissions_currency__c, rms_peril_region__c, rms_version__c,
        anemometers__c, last_modify_date_user__c, last_modiofied_by_user__c,
        number_of_anemometer_ws_triggers__c, number_of_ciac_triggers__c,
        number_of_proxy_ws_triggers__c, number_of_triggers__c, hurricane_coverage_type__c,
        modeling_provider__c
    ) VALUES (
        source.id, source.owner_id, source.is_deleted, source.name, source.record_type_id,
        source.created_date, source.created_by_id, source.last_modified_date,
        source.last_modified_by_id, source.system_modstamp, source.last_viewed_date,
        source.last_referenced_date, source.calculation_agent_expense__c, source.coverage__c,
        source.expected_loss__c, source.inland_circle_factor__c, source.insurance_state_tax__c,
        source.limit_of_insurance__c, source.loss_cost_multiplier_lcm__c,
        source.market_broker_commissions__c, source.minimum_rate__c,
        source.nmis_mga_commissions__c, source.other_brokerage_commissions__c,
        source.policy_fee__c, source.product__c, source.tax_exempt__c, source.transaction__c,
        source.underwriting_fee__c, source.weatherflow_maintenance_expense__c,
        source.wholesaler_retailer_commissions__c, source.adjusted_base_premium__c,
        source.adjusted_base_rate__c, source.adjusted_expected_loss__c, source.annual_premium__c,
        source.calculation_agent_expense_cost__c, source.gross_premium_excl_taxes_and_fees__c,
        source.gross_rate_excl_taxes_and_fees__c, source.net_premium__c, source.net_rate__c,
        source.non_adjusted_base_rate__c, source.taxable_premium__c, source.total_commissions__c,
        source.weatherflow_maintenance_cost__c, source.policy__c,
        source.market_broker_commission_currency__c, source.all_in_rate__c,
        source.anemometer_rating_factor__c, source.issued_policy__c, source.quote__c,
        source.adjusted_base_premium_om__c, source.adjusted_base_rate_om__c,
        source.adjusted_expected_loss_om__c, source.all_in_rate_om__c, source.annual_premium_om__c,
        source.calculation_agent_expense_cost_om__c,
        source.gross_premium_excl_taxes_and_fees_om__c,
        source.gross_rate_excl_taxes_and_fees_om__c, source.net_premium_om__c,
        source.net_rate_om__c, source.non_adjusted_base_rate_om__c, source.taxable_premium_om__c,
        source.total_commissions_om__c, source.weatherflow_maintenance_cost_om__c,
        source.adjusted_loss_factor__c, source.mga_commission__c,
        source.other_surplus_line_taxes_amount__c, source.policy_administrator_fee__c,
        source.rating_calculation__c, source.rating_type__c, source.retail_commsion_ammount__c,
        source.surplus_lines_taxes_amount_1__c, source.surplus_lines_taxes_amount_2__c,
        source.surplus_lines_taxes_description_1__c, source.surplus_lines_taxes_description_2__c,
        source.last_modified_date_user__c, source.last_modified_by_user__c,
        source.is_current_structure__c, source.manual_override__c, source.original_currency__c,
        source.day_s_exchange__c, source.limit_in_original_currency__c,
        source.premium_in_original_currency__c, source.stamp_date__c, source.maximum_rate__c,
        source.calculate_rates__c, source.other_brokerage_commissions_currency__c,
        source.rms_peril_region__c, source.rms_version__c, source.anemometers__c,
        source.last_modify_date_user__c, source.last_modiofied_by_user__c,
        source.number_of_anemometer_ws_triggers__c, source.number_of_ciac_triggers__c,
        source.number_of_proxy_ws_triggers__c, source.number_of_triggers__c,
        source.hurricane_coverage_type__c, source.modeling_provider__c
    );

ALTER TASK SALESFORCE.STRUCTURE_MERGE_TASK RESUME;