USE ROLE ACCOUNTADMIN;
USE DATABASE {env}_NMIS_ETL_PIPELINE;

CREATE SCHEMA IF NOT EXISTS SALESFORCE;

CREATE FILE FORMAT IF NOT EXISTS SALESFORCE.PARQUET_FORMAT
  TYPE               = PARQUET
  SNAPPY_COMPRESSION = TRUE;

CREATE OR REPLACE STORAGE INTEGRATION {env}_S3_NMIS_ETL_DATA_LAKE_INTEGRATION
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = S3
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::{account}:role/{iam_role}'
  STORAGE_ALLOWED_LOCATIONS = ('s3://{bucket}/raw/');

CREATE OR REPLACE STAGE SALESFORCE.SALESFORCE_RAW
  STORAGE_INTEGRATION = DEV_S3_NMIS_ETL_DATA_LAKE_INTEGRATION
  URL                 = 's3://{bucket}/raw/'
  FILE_FORMAT         = SALESFORCE.PARQUET_FORMAT;