-- Prerequisites: V1.3.0 applied, snowpipe_sqs_arn set in SSM, terraform apply run.
-- Pass values via --vars: database

USE DATABASE {{ database }};

CREATE STREAM IF NOT EXISTS SALESFORCE.POLICY_STREAM
  ON TABLE SALESFORCE.POLICY_STAGING
  APPEND_ONLY = FALSE;

CREATE TASK IF NOT EXISTS SALESFORCE.POLICY_MERGE_TASK
  WAREHOUSE = COMPUTE_WH
  SCHEDULE  = '5 MINUTE'
  WHEN SYSTEM$STREAM_HAS_DATA('SALESFORCE.POLICY_STREAM')
AS
MERGE INTO SALESFORCE.POLICY t
USING (
  SELECT * EXCLUDE (METADATA$ACTION, METADATA$ISUPDATE, METADATA$ROW_ID)
  FROM SALESFORCE.POLICY_STREAM
  QUALIFY ROW_NUMBER() OVER (PARTITION BY id ORDER BY last_modified_date DESC) = 1
) s ON t.id = s.id
WHEN MATCHED AND s.is_deleted = TRUE       THEN DELETE
WHEN MATCHED                               THEN UPDATE SET *
WHEN NOT MATCHED AND s.is_deleted = FALSE  THEN INSERT *;

ALTER TASK SALESFORCE.POLICY_MERGE_TASK RESUME;